/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Mentions
         * @description List mentions with optional filtering. Supports drill-through from all dashboard pages.
         */
        get: operations["list_mentions_api_mentions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentions/{mention_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mention
         * @description Retrieve a single mention by ID.
         */
        get: operations["get_mention_api_mentions__mention_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kpis
         * @description Top-line KPIs: total mentions, overall sentiment score, WoW delta, rising aspects.
         */
        get: operations["get_kpis_api_overview_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Timeseries
         * @description Daily sentiment timeseries, filterable by brand/category.
         */
        get: operations["get_timeseries_api_overview_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview/share_of_voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Share Of Voice
         * @description Share-of-voice by brand. Optionally filtered by category.
         */
        get: operations["get_share_of_voice_api_overview_share_of_voice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description List all products with summary stats (brand, category, overall score, mention count).
         */
        get: operations["list_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_model}/aspects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product Aspects
         * @description Per-product aspect breakdown with trend and severity.
         */
        get: operations["get_product_aspects_api_products__product_model__aspects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_model}/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product Timeseries
         * @description Per-product daily sentiment timeseries.
         */
        get: operations["get_product_timeseries_api_products__product_model__timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_model}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product Forecast
         * @description 4-week forward sentiment forecast using exponentially-weighted linear projection.
         *
         *     Use ?explain=true to return the formula documentation instead of forecast data.
         *
         *     Method: heuristic projection, NOT an LLM simulation. See forecast.py for full formula.
         *     low_confidence=true when mention_count < 50 OR window_days < 14.
         */
        get: operations["get_product_forecast_api_products__product_model__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Platform Comparison
         * @description Cross-platform aspect sentiment grid.
         *     Rows = platforms, columns = aspects. Cell = sentiment score + mention volume.
         */
        get: operations["get_platform_comparison_api_platforms_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topics
         * @description Emerging topics clustered by aspect, sorted by momentum.
         *     Each topic includes exemplar quotes for evidence traceability.
         */
        get: operations["get_topics_api_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/comparative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Comparative Topics
         * @description Share-of-aspect comparison between two brands.
         *     Shows which aspects each brand dominates in consumer conversation.
         */
        get: operations["get_comparative_topics_api_topics_comparative_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Rising negative aspect alerts sorted by severity.
         *     Use ?acknowledged=false for active alerts, ?acknowledged=true for history.
         *     Use ?platforms=reddit&platforms=amazon to filter by source platform.
         */
        get: operations["list_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Acknowledge Alert
         * @description Mark an alert as acknowledged.
         */
        patch: operations["acknowledge_alert_api_alerts__alert_id__acknowledge_patch"];
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Simulation
         * @description Simulate consumer segment reactions to a hypothetical scenario.
         *
         *     Grounds the LLM in real mention data �� passes 5-10 actual consumer reviews
         *     as context so the LLM reasons over observed consumer text, not product names alone.
         *
         *     Caches by (scenario, product_model, filter_context_hash) to prevent cost blowup.
         *     Times out at 30 seconds with a structured error response.
         *
         *     NOTE: This is a simulation, not a measurement. The overall_disclaimer field
         *     makes this explicit per charter ��6.2 anti-theater requirements.
         */
        post: operations["run_simulation_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Smoke-test endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertAcknowledgeResponse */
        AlertAcknowledgeResponse: {
            /** Alert Id */
            alert_id: string;
            /** Acknowledged */
            acknowledged: boolean;
        };
        /** AlertEvent */
        AlertEvent: {
            /** Alert Id */
            alert_id: string;
            /** Product Model */
            product_model?: string | null;
            brand: components["schemas"]["Brand"];
            /** Aspect */
            aspect: string;
            /**
             * Severity
             * @description Composite severity score
             */
            severity: number;
            /**
             * Score Drop
             * @description How much the aspect score dropped
             */
            score_drop: number;
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
            /**
             * Acknowledged
             * @default false
             */
            acknowledged: boolean;
            /** Exemplar Mentions */
            exemplar_mentions?: components["schemas"]["Mention"][];
            /**
             * Platforms
             * @description Distinct set of source platforms from exemplar_mentions[*].source_platform
             */
            platforms?: components["schemas"]["SourcePlatform"][];
        };
        /** AlertListResponse */
        AlertListResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["AlertEvent"][];
        };
        /** AspectSentiment */
        AspectSentiment: {
            /**
             * Name
             * @description Canonical aspect name, e.g. 'suction', 'battery', 'brushroll'
             */
            name: string;
            polarity: components["schemas"]["Polarity"];
            /** Score */
            score: number;
            /** Confidence */
            confidence: number;
            /**
             * Snippet
             * @description Text fragment that triggered this aspect extraction
             */
            snippet: string;
        };
        /** AspectTrend */
        AspectTrend: {
            /**
             * Aspect
             * @description Canonical aspect name
             */
            aspect: string;
            /** Mention Count */
            mention_count: number;
            /** Avg Score */
            avg_score: number;
            /**
             * Trend Delta
             * @description 30-day score change
             */
            trend_delta: number;
            /**
             * Severity
             * @description volume x magnitude x recency composite
             */
            severity: number;
            /**
             * Sparkline
             * @description Weekly scores, most recent last
             */
            sparkline: number[];
        };
        /**
         * Brand
         * @enum {string}
         */
        Brand: "shark" | "ninja" | "dyson" | "irobot" | "roborock" | "kitchenaid" | "breville" | "cuisinart" | "keurig" | "delonghi" | "other";
        /** BrandShare */
        BrandShare: {
            brand: components["schemas"]["Brand"];
            /** Mention Count */
            mention_count: number;
            /**
             * Share
             * @description Fraction of total mentions
             */
            share: number;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "robot_vacuum" | "cordless_stick" | "upright" | "air_fryer" | "pressure_cooker" | "blender" | "ice_cream_maker" | "coffee" | "air_purifier" | "hair_tool" | "other";
        /** ComparativePair */
        ComparativePair: {
            brand: components["schemas"]["Brand"];
            /**
             * Aspect
             * @description Canonical aspect name
             */
            aspect: string;
            polarity: components["schemas"]["Polarity"];
            /** Score */
            score: number;
        };
        /** ComparativeTopicResponse */
        ComparativeTopicResponse: {
            brand_a: components["schemas"]["Brand"];
            brand_b: components["schemas"]["Brand"];
            /** Share Of Aspect */
            share_of_aspect: components["schemas"]["ShareOfAspect"][];
        };
        /** DerivedSentiment */
        DerivedSentiment: {
            overall_sentiment: components["schemas"]["SentimentLabel"];
            /**
             * Compound Score
             * @description Single scalar for charting
             */
            compound_score: number;
            /**
             * Confidence
             * @description Pipeline confidence in this result
             */
            confidence: number;
            /**
             * Sarcasm Flag
             * @description True if sarcasm heuristics fired
             */
            sarcasm_flag: boolean;
            /** Aspects */
            aspects?: components["schemas"]["AspectSentiment"][];
            /**
             * Comparative Pairs
             * @description Only populated when a comparative claim is detected
             */
            comparative_pairs?: components["schemas"]["ComparativePair"][] | null;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Date
             * @description ISO date YYYY-MM-DD
             */
            date: string;
            /** Projected Score */
            projected_score: number;
            /** Confidence Lower */
            confidence_lower: number;
            /** Confidence Upper */
            confidence_upper: number;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Product Model */
            product_model: string;
            /** Historical */
            historical: components["schemas"]["TimeseriesPoint"][];
            /** Forecast */
            forecast: components["schemas"]["ForecastPoint"][];
            /**
             * Method Label
             * @description Human-readable label for the forecasting method used
             */
            method_label: string;
            /** Input Mention Count */
            input_mention_count: number;
            /** Input Window Days */
            input_window_days: number;
            /**
             * Low Confidence
             * @description True when mention_count < 50 OR window_days < 14
             */
            low_confidence: boolean;
            /**
             * Caveats
             * @description Reasons for low confidence or forecast limitations
             */
            caveats?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Mention */
        Mention: {
            /**
             * Mention Id
             * @description Stable UUID identifier
             */
            mention_id: string;
            source_platform: components["schemas"]["SourcePlatform"];
            /**
             * Source Url
             * @description URL to original mention; null for closed sources
             */
            source_url?: string | null;
            /**
             * Author Handle
             * @description Anonymized/hashed author handle
             */
            author_handle?: string | null;
            /**
             * Posted At
             * Format: date-time
             * @description When the mention was published (UTC)
             */
            posted_at: string;
            /**
             * Ingested At
             * Format: date-time
             * @description When our pipeline processed it (UTC)
             */
            ingested_at: string;
            brand: components["schemas"]["Brand"];
            category: components["schemas"]["Category"];
            /**
             * Product Model
             * @description Specific SKU name if available
             */
            product_model?: string | null;
            /**
             * Text
             * @description Raw mention text, pre-NLP
             */
            text: string;
            /**
             * Rating
             * @description Source-provided star rating if available
             */
            rating?: number | null;
            /**
             * Language
             * @description ISO-639-1 language code
             * @default en
             */
            language: string;
            derived: components["schemas"]["DerivedSentiment"];
            /**
             * Record Type
             * @description 'review' for normal mentions; 'recall' for CPSC recall records
             * @default review
             * @enum {string}
             */
            record_type: "review" | "recall";
        };
        /** MentionFilter */
        MentionFilter: {
            platform?: components["schemas"]["SourcePlatform"] | null;
            brand?: components["schemas"]["Brand"] | null;
            category?: components["schemas"]["Category"] | null;
            /** Product Model */
            product_model?: string | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * Topic Id
             * @description Filter mentions by topic cluster ID
             */
            topic_id?: string | null;
        };
        /** MentionListResponse */
        MentionListResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["Mention"][];
        };
        /** OverviewKPIs */
        OverviewKPIs: {
            /** Total Mentions */
            total_mentions: number;
            /** Overall Score */
            overall_score: number;
            /**
             * Wow Delta
             * @description Week-over-week score change
             */
            wow_delta: number;
            /**
             * Top Rising Negative
             * @description Aspect names with worst score drops
             */
            top_rising_negative: string[];
            /**
             * Top Rising Positive
             * @description Aspect names with best score gains
             */
            top_rising_positive: string[];
        };
        /** PlatformAspectCell */
        PlatformAspectCell: {
            platform: components["schemas"]["SourcePlatform"];
            /** Aspect */
            aspect: string;
            /** Sentiment Score */
            sentiment_score: number;
            /** Mention Count */
            mention_count: number;
        };
        /** PlatformComparisonResponse */
        PlatformComparisonResponse: {
            /** Grid */
            grid: components["schemas"]["PlatformAspectCell"][];
            /**
             * Top Topics By Platform
             * @description platform -> top topic labels
             */
            top_topics_by_platform: {
                [key: string]: string[];
            };
        };
        /**
         * Polarity
         * @enum {string}
         */
        Polarity: "positive" | "negative" | "neutral" | "mixed";
        /** ProductAspectResponse */
        ProductAspectResponse: {
            /** Product Model */
            product_model: string;
            brand: components["schemas"]["Brand"];
            category: components["schemas"]["Category"];
            /** Aspects */
            aspects: components["schemas"]["AspectTrend"][];
            /** Exemplar Mentions */
            exemplar_mentions: components["schemas"]["Mention"][];
        };
        /** ProductSummary */
        ProductSummary: {
            brand: components["schemas"]["Brand"];
            category: components["schemas"]["Category"];
            /** Product Model */
            product_model: string;
            /** Overall Score */
            overall_score: number;
            /** Mention Count */
            mention_count: number;
        };
        /**
         * SentimentLabel
         * @enum {string}
         */
        SentimentLabel: "positive" | "negative" | "neutral" | "mixed";
        /** ShareOfAspect */
        ShareOfAspect: {
            brand: components["schemas"]["Brand"];
            /** Aspect */
            aspect: string;
            /**
             * Mention Share
             * @description Fraction of all mentions for this aspect
             */
            mention_share: number;
            /** Avg Score */
            avg_score: number;
        };
        /** ShareOfVoiceResponse */
        ShareOfVoiceResponse: {
            /** Total Mentions */
            total_mentions: number;
            /** Brands */
            brands: components["schemas"]["BrandShare"][];
        };
        /** SimulatedSegment */
        SimulatedSegment: {
            /**
             * Segment Label
             * @description Consumer segment label, e.g. 'Price-sensitive first-time buyers'
             */
            segment_label: string;
            /**
             * Predicted Reaction
             * @enum {string}
             */
            predicted_reaction: "positive" | "negative" | "mixed" | "neutral";
            /**
             * Confidence Narrative
             * @description Plain English 2-3 sentence explanation of why this segment reacts this way
             */
            confidence_narrative: string;
            /**
             * Key Quotes Used
             * @description Actual review text snippets from grounding mentions that informed this segment
             */
            key_quotes_used?: string[];
        };
        /** SimulationRequest */
        SimulationRequest: {
            /**
             * Scenario
             * @description Natural language scenario, e.g. 'What if Shark launched a $99 budget version?'
             */
            scenario: string;
            /**
             * Product Model
             * @description Product context anchor �� filters grounding mentions to this SKU if provided
             */
            product_model?: string | null;
            /** @description Current dashboard filter state for grounding mention selection */
            filter_context?: components["schemas"]["MentionFilter"] | null;
        };
        /** SimulationResult */
        SimulationResult: {
            /**
             * Scenario
             * @description Echo of the input scenario
             */
            scenario: string;
            /** Product Model */
            product_model?: string | null;
            /**
             * Segments
             * @description 3-5 consumer segments with predicted reactions
             */
            segments: components["schemas"]["SimulatedSegment"][];
            /**
             * Overall Disclaimer
             * @description Anti-theater honesty label. MUST contain: 'Simulated reaction based on LLM heuristic, not empirical behavior modeling.'
             * @default Simulated reaction based on LLM heuristic, not empirical behavior modeling.
             */
            overall_disclaimer: string;
            /**
             * Model Used
             * @description LLM model ID used for this simulation
             */
            model_used: string;
            /**
             * Tokens Consumed
             * @description Total tokens used (prompt + completion)
             */
            tokens_consumed: number;
        };
        /**
         * SourcePlatform
         * @enum {string}
         */
        SourcePlatform: "reddit" | "amazon" | "youtube" | "trustpilot" | "twitter" | "other";
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /**
             * Date
             * @description ISO date YYYY-MM-DD
             */
            date: string;
            /** Score */
            score: number;
            /** Mention Count */
            mention_count: number;
        };
        /** TimeseriesResponse */
        TimeseriesResponse: {
            /** Series */
            series: components["schemas"]["TimeseriesPoint"][];
            brand?: components["schemas"]["Brand"] | null;
            category?: components["schemas"]["Category"] | null;
        };
        /** TopicCluster */
        TopicCluster: {
            /** Topic Id */
            topic_id: string;
            /** Label */
            label: string;
            /** Mention Count */
            mention_count: number;
            /** Avg Score */
            avg_score: number;
            /**
             * Momentum
             * @description Recent growth rate
             */
            momentum: number;
            /** Exemplar Quotes */
            exemplar_quotes: string[];
            /** Trend */
            trend: components["schemas"]["TimeseriesPoint"][];
            /**
             * Is Novel
             * @description True when momentum > 0.3, mention_count < 25, and first_seen_at within last 14 days
             * @default false
             */
            is_novel: boolean;
        };
        /** TopicExplorerResponse */
        TopicExplorerResponse: {
            /** Topics */
            topics: components["schemas"]["TopicCluster"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_mentions_api_mentions_get: {
        parameters: {
            query?: {
                platform?: components["schemas"]["SourcePlatform"] | null;
                brand?: components["schemas"]["Brand"] | null;
                category?: components["schemas"]["Category"] | null;
                product_model?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
                topic_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mention_api_mentions__mention_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mention_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mention"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kpis_api_overview_kpis_get: {
        parameters: {
            query?: {
                brand?: components["schemas"]["Brand"] | null;
                category?: components["schemas"]["Category"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewKPIs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeseries_api_overview_timeseries_get: {
        parameters: {
            query?: {
                brand?: components["schemas"]["Brand"] | null;
                category?: components["schemas"]["Category"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_of_voice_api_overview_share_of_voice_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareOfVoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_products_get: {
        parameters: {
            query?: {
                brand?: components["schemas"]["Brand"] | null;
                category?: components["schemas"]["Category"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_aspects_api_products__product_model__aspects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_model: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAspectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_timeseries_api_products__product_model__timeseries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_model: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_forecast_api_products__product_model__forecast_get: {
        parameters: {
            query?: {
                /** @description Return formula documentation instead of forecast data */
                explain?: boolean;
            };
            header?: never;
            path: {
                product_model: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platform_comparison_api_platforms_comparison_get: {
        parameters: {
            query?: {
                brand?: components["schemas"]["Brand"] | null;
                category?: components["schemas"]["Category"] | null;
                product_model?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topics_api_topics_get: {
        parameters: {
            query?: {
                brand?: components["schemas"]["Brand"] | null;
                category?: components["schemas"]["Category"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicExplorerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparative_topics_api_topics_comparative_get: {
        parameters: {
            query: {
                /** @description First brand for comparison */
                brand_a: components["schemas"]["Brand"];
                /** @description Second brand for comparison */
                brand_b: components["schemas"]["Brand"];
                category?: components["schemas"]["Category"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparativeTopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_alerts_get: {
        parameters: {
            query?: {
                brand?: components["schemas"]["Brand"] | null;
                category?: components["schemas"]["Category"] | null;
                /** @description Filter by acknowledged state. ?acknowledged=false for active, ?acknowledged=true for history */
                acknowledged?: boolean | null;
                /** @description Filter alerts to those involving any of the specified platforms */
                platforms?: components["schemas"]["SourcePlatform"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_api_alerts__alert_id__acknowledge_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertAcknowledgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_simulation_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
